<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('countries')->delete();
      $data = array(
          ['nome_pt_br' => '', 'nome_eng' => 'Afghanistan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Åland Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Albania', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Algeria', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'American Samoa', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Andorra', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Angola', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Anguilla', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Antarctica', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Antigua and Barbuda', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Argentina', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Armenia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Aruba', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Ascension Island', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Australia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Austria', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Azerbaijan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bahamas', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bahrain', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bangladesh', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Barbados', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Belarus', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Belgium', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Belize', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Benin', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bermuda', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bhutan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bolivia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bosnia and Herzegovina', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Botswana', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bouvet Island', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Brazil', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'British Indian Ocean Territory', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'British Virgin Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Brunei', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Bulgaria', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Burkina Faso', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Burundi', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cambodia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cameroon', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Canada', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Canary Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cape Verde', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Caribbean Netherlands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cayman Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Central African Republic', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Ceuta and Melilla', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Chad', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Chile', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'China', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Christmas Island', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Clipperton Island', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cocos (Keeling) Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Colombia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Comoros', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Congo (DRC)', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Congo (Republic)', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cook Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Costa Rica', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Côte d’Ivoire', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Croatia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cuba', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Curaçao', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Cyprus', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Czech Republic', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Denmark', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Diego Garcia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Djibouti', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Dominica', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Dominican Republic', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Ecuador', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Egypt', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'El Salvador', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Equatorial Guinea', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Eritrea', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Estonia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Ethiopia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Falkland Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Faroe Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Fiji', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Finland', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'France', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'French Guiana', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'French Polynesia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'French Southern Territories', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Gabon', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Gambia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Georgia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Germany', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Ghana', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Gibraltar', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Greece', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Greenland', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Grenada', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Guadeloupe', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Guam', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Guatemala', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Guernsey', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Guinea', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Guinea-Bissau', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Guyana', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Haiti', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Heard & McDonald Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Honduras', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Hong Kong', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Hungary', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Iceland', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'India', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Indonesia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Iran', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Iraq', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Ireland', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Isle of Man', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Israel', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Italy', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Jamaica', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Japan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Jersey', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Jordan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Kazakhstan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Kenya', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Kiribati', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Kosovo', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Kuwait', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Kyrgyzstan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Laos', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Latvia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Lebanon', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Lesotho', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Liberia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Libya', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Liechtenstein', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Lithuania', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Luxembourg', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Macau', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Macedonia (FYROM)', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Madagascar', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Malawi', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Malaysia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Maldives', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Mali', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Malta', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Marshall Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Martinique', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Mauritania', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Mauritius', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Mayotte', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Mexico', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Micronesia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Moldova', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Monaco', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Mongolia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Montenegro', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Montserrat', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Morocco', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Mozambique', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Myanmar (Burma)', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Namibia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Nauru', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Nepal', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Netherlands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'New Caledonia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'New Zealand', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Nicaragua', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Niger', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Nigeria', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Niue', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Norfolk Island', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Northern Mariana Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'North Korea', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Norway', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Oman', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Pakistan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Palau', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Palestine', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Panama', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Papua New Guinea', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Paraguay', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Peru', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Philippines', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Pitcairn Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Poland', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Portugal', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Puerto Rico', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Qatar', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Réunion', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Romania', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Russia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Rwanda', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Saint Barthélemy', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Saint Helena', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Saint Kitts and Nevis', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Saint Lucia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Saint Martin', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Saint Pierre and Miquelon', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Samoa', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'San Marino', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'São Tomé and Príncipe', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Saudi Arabia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Senegal', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Serbia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Seychelles', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Sierra Leone', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Singapore', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Sint Maarten', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Slovakia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Slovenia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Solomon Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Somalia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'South Africa', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'South Georgia & South Sandwich Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'South Korea', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'South Sudan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Spain', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Sri Lanka', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'St. Vincent & Grenadines', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Sudan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Suriname', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Svalbard and Jan Mayen', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Swaziland', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Sweden', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Switzerland', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Syria', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Taiwan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Tajikistan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Tanzania', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Thailand', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Timor-Leste', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Togo', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Tokelau', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Tonga', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Trinidad and Tobago', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Tristan da Cunha', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Tunisia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Turkey', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Turkmenistan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Turks and Caicos Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Tuvalu', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'U.S. Outlying Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'U.S. Virgin Islands', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Uganda', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Ukraine', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'United Arab Emirates', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'United Kingdom', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'United States', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Uruguay', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Uzbekistan', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Vanuatu', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Vatican City', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Venezuela', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Vietnam', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Wallis and Futuna', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Western Sahara', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Yemen', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Zambia', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
          ['nome_pt_br' => '', 'nome_eng' => 'Zimbabwe', 'descricao' => '', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')]
      );
      DB::table('countries')->insert($data);
    }
}
